stages:
    - build
    - test 
variables:
    NODE_IMAGE: node:18
workflow:
    auto_cancel:
        on_job_failure: all
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          when: always
        - when: never
before_script:
    - apt-get update -qy
    - apt-get install -y nodejs npm
    - npm install -g yarn
build:
    stage: build
    script:
        - yarn install --force
        - yarn cache clean
        - yarn build --verbose --force
    artifacts:
        expire_in: 1 days
        when: on_success
        paths:
            - node_modules/
test:
    stage: test
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    dependencies:
        - build
    script:
        - yarn test
    artifacts:
        when: always
        reports:
            junit:
                - junit.xml