// Data Hooks - mixed exports (some default, some named)
export { default as useAnalyticsData } from '@/hooks/useAnalyticsData'
export { useDiseaseData } from '@/hooks/useDiseaseData'
export { useCacheStorage } from '@/hooks/useCacheStorage'
export { useClimateData } from '@/hooks/useClimateData'
export { default as useDataFetchStatus } from '@/hooks/useDataFetchStatus'
export { useDataManagement } from '@/hooks/useDataManagement'
export { useDiseaseTrend } from '@/hooks/useDiseaseTrend'
export { useExecuteQuery } from '@/hooks/useExecuteQuery'
export { default as useForecastData } from '@/hooks/useForecastData'
export { useGeoData } from '@/hooks/useGeoData'
export { default as useHistoricData } from '@/hooks/useHistoricData'
export { default as useFetchHistoricData } from '@/hooks/useFetchHistoricData'
export { default as useIndicatorDataManager } from '@/hooks/useIndicatorDataManager'
export { useMinMaxValues } from '@/hooks/useMinMaxValue'
export { default as useOrgUnitDetails } from '@/hooks/useOrgUnitDetails'
export { default as useOrgUnitLevels } from '@/hooks/useOrgUnitLevels'
export { default as useOrgUnits } from '@/hooks/useOrgUnits'
export { usePridecUpdate } from '@/hooks/usePridecDataUpdate'
export { default as usePridecOrgUnits } from '@/hooks/usePridecOrgUnits'
export { default as useSequentialForecastElements } from '@/hooks/useSequentialForecastElements'

// Utility Hooks
export { useResponsive, useWidth } from '@/hooks/use-responsive'
