export const columns = [
    {
        accessorKey: 'municipality',
        header: 'Commune',
        size: 150,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: true,
    },
    {
        accessorKey: 'orgUnitName',
        header: 'Fokontany',
        size: 150,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: false,
    },
    {
        accessorKey: 'periodName',
        header: 'Mois',
        size: 150,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: false,
        enableGlobalFilter: false,
    },
    {
        accessorKey: 'min',
        header: 'Estimation min.',
        size: 100,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: true,
        enableGlobalFilter: false,
    },
    {
        accessorKey: 'mean',
        header: 'Estimation moyenne',
        size: 100,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: true,
        enableGlobalFilter: false,
    },
    {
        accessorKey: 'max',
        header: 'Estimation max.',
        size: 100,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: true,
        enableGlobalFilter: false,
    },
]
