import i18n from '../../locales'

export const columns = [
    {
        id: 1,
        accessorKey: 'parentName',
        header: undefined,
        size: 150,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: true,
    },
    {
        id: 2,
        accessorKey: 'orgUnitName',
        header: undefined,
        size: 150,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: false,
    },
    {
        id: 3,
        accessorKey: 'periodName',
        header: i18n.t('Month'),
        size: 150,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: false,
        enableGlobalFilter: false,
    },
    {
        id: 4,
        accessorKey: 'lowci',
        header: i18n.t('Minimum estimate'),
        size: 100,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: true,
        enableGlobalFilter: false,
    },
    {
        id: 5,
        accessorKey: 'avg',
        header: i18n.t('Average estimate'),
        size: 100,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: true,
        enableGlobalFilter: false,
    },
    {
        id: 6,
        accessorKey: 'uppci',
        header: i18n.t('Maximum estimate'),
        size: 100,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: true,
        enableGlobalFilter: false,
    },
]
