export const columns = [
    {
        id: 1,
        accessorKey: 'parentName',
        header: undefined,
        size: 150,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: true,
    },
    {
        id: 2,
        accessorKey: 'orgUnitName',
        header: undefined,
        size: 150,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: false,
    },
    {
        id: 3,
        accessorKey: 'periodName',
        header: 'Mois',
        size: 150,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: false,
        enableGlobalFilter: false,
    },
    {   
        id: 4,
        accessorKey: 'lowci',
        header: 'Estimation min.',
        size: 100,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: true,
        enableGlobalFilter: false,
    },
    {
        id: 5,
        accessorKey: 'avg',
        header: 'Estimation moyenne',
        size: 100,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: true,
        enableGlobalFilter: false,
    },
    {
        id: 6,
        accessorKey: 'uppci',
        header: 'Estimation max.',
        size: 100,
        visible: true,
        enableColumnActions: false,
        enableHideColumn: true,
        enableGlobalFilter: false,
    },
]
